### ISSUE TITLE
Unclear documentation on which "Page" fields are optional

### ISSUE THREAD

**Issue by vinczebalazs** [schedjoules/swift-api-client#10]

**Comment by vinczebalazs** [comment]
The `API` documentation is unclear about which exact properties are optional on a `Page` response. 
After clearing these up, the protocols regarding `Page` models need to be updated.

**Comment by rutgerg** [comment]
Can you give an example of something unclear?

**Comment by vinczebalazs** [comment]
Everything has been cleared up, closing issue.
