### ISSUE TITLE
Weather calendars only show metric units

### ISSUE THREAD

**Issue by wilfredstegeman** [schedjoules/swift-api-client#100]
When subscribing to a weather calendar, if you select imperial units instead of metric the resulting calendar still displays metric values. 

![IMG_1909.PNG](https://images.zenhubusercontent.com/5800a3f895e42b6c5baa75a7/b3afccb4-0477-4a9e-acc4-8a31e9a6ad18) 

![IMG_1908.PNG](https://images.zenhubusercontent.com/5800a3f895e42b6c5baa75a7/ed10b285-e567-46ac-b618-91dd0f1dfddb)

**Comment by rutgerg** [comment]
Yep I see it in the code. Must have been there since we switched to Openweather dat. @Edhoru what value is passed through the client if a user changes to imperial units?

**Comment by Edhoru** [comment]
Fixed in: https://github.com/schedjoules/ios-public-calendars-sdk/commit/c4ccf1905a116c5610cabb98ac20e5dce133e728
