### ISSUE TITLE
Crash when subscription returns an error instead of data parsable to JSONSubscription

### ISSUE THREAD

**Issue by Edhoru** [schedjoules/swift-api-client#81]
When trying to subscribe to that calendar there is a crash caused by the sdk not being able to Decode the JSON response. The crash log on Xcode is:

Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.keyNotFound(PageKeys(stringValue: "subscriptionId", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key PageKeys(stringValue: \"subscriptionId\", intValue: nil) (\"subscriptionId\").", underlyingError: nil)): file /Users/edhoru/Documents/GitHub/ios-public-calendars-sdk/Pods/SchedJoulesApiClient/ApiClient/Source/Subscriptions/Queries/SubscriptionStatusQuery.swift, line 48
2019-07-19 05:32:30.716145-0500 iOS-SDK[1634:627354] Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.keyNotFound(PageKeys(stringValue: "subscriptionId", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key PageKeys(stringValue: \"subscriptionId\", intValue: nil) (\"subscriptionId\").", underlyingError: nil)): file /Users/edhoru/Documents/GitHub/ios-public-calendars-sdk/Pods/SchedJoulesApiClient/ApiClient/Source/Subscriptions/Queries/SubscriptionStatusQuery.swift, line 48

**Comment by rutgerg** [comment]
What is special about Formula E compared to others? Calendar file seems ok. Where does json come from?

**Comment by wilfredstegeman** [comment]
I'm able to successfully subscribe to the Formula E calendar.

**Comment by Edhoru** [comment]
When using the api key "d80107...." instead of the subscription I get this:

    subscriptionStatusCode = 404;
    subscriptionStatusMessage = "No record present";

The api doesn't handle anything that doesn't conform to the JSONSubscription structure, which is:
    let subscriptionId: String
    let expirationDate: TimeInterval
    let purchaseDate: TimeInterval
    let subscriptionStatusCode: Int
    let subscriptionStatusMessage: String
    let transactionIds: [UInt64]

So we are getting the crash, here is the PR https://github.com/schedjoules/swift-api-client/pull/83

**Comment by Edhoru** [comment]
I just edited the name from Crash when subscribing to "Formula E" calendar to Crash when subscription returns an error instead of data parsable to JSONSubscription better reflect the issue
