### ISSUE TITLE
Add option to load the weather calendar from the api

### ISSUE THREAD

**Issue by Edhoru** [schedjoules/swift-api-client#82]
The weather calendar doesn't follow the same logic as the other calendars, since the it uses the units defined in the client end, we have to add the method so clients don't make the request directly to our backend.

**Comment by Edhoru** [comment]
First part: loading the weather settings is up: https://github.com/schedjoules/swift-api-client/commit/55ab98bba25072cc359fc70af375976fe54f69bb

Second part in progress

**Comment by Edhoru** [comment]
@rutgerg @dmfs the PR is ready for review https://github.com/schedjoules/swift-api-client/pull/87

**Comment by dmfs** [comment]
I'll look into that later this evening.
