### ISSUE TITLE
iPad support Swift SDK

### ISSUE THREAD

**Issue by wilfredstegeman** [schedjoules/swift-api-client#99]
It looks like Swift SDK is not supporting iPad. Check via the link below the video for (a part of) the issues 

https://www.dropbox.com/s/begpjnhwjsgf85v/191114%20iCalendar%20iPad%20Screen%20Recording.mov?dl=0

**Comment by wilfredstegeman** [comment]
What is the status of this?

**Comment by Edhoru** [comment]
Done, for tracking purposes the issue was moved to https://github.com/schedjoules/ios-public-calendars-sdk/issues/111
